version: '3.4'

services:
  catalogdb:
    image: mongo
  
  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin.portal:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  shopping.api.gateway:
    image: ${DOCKER_REGISTRY-}shoppingapigateway
    build:
      context: .
      dockerfile: Gateways/Shopping.API.Gateway/Dockerfile

  shopping.api.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingapiaggregator
    build:
      context: .
      dockerfile: Gateways/Shopping.API.Aggregator/Dockerfile

  aspnetrunbasics:
    image: ${DOCKER_REGISTRY-}aspnetrunbasics
    build:
      context: .
      dockerfile: WebApps/AspnetRunBasics/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.18

  shopping.app.webstatus:
    image: ${DOCKER_REGISTRY-}shoppingappwebstatus
    build:
      context: .
      dockerfile: WebApps/Shopping.App.WebStatus/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  pgadmin_data:
  portainer_data:
  elasticsearch-data:








